version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "03:00"
      timezone: "  "

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      time: "03:00"
      timezone: "  "
